print("Hello GitHub!")
name = input("What is your name? ")
print("Hello", name)
print("This line was added directly on GitHub.")
print("This line was added directly on github by ehtisham.")
print("This line was added directly on github by sir pirzada.")
